version: "~> 1.0"

os: linux
language: shell

env:
  global:
    - HUGO_VERSION=0.61.0

git:
  quiet: true

notifications:
  email: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y unzip

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb

script:
  - hugo

deploy:
  provider: pages:git
  edge: true
  local_dir: public
  on:
    repo: pollen-robotics/website
    branch: master
