version: "~> 1.0"
os: linux
language: shell
env:
  global:
    - HUGO_VERSION=0.61.0
git:
  quiet: true
notifications:
  email: false
before_install:
  - sudo apt-get update
  - sudo apt-get install -y unzip
install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
script:
  - hugo
deploy:
  provider: pages:git
  edge: true
  local_dir: public
  fqdn: www.pollen-robotics.com
  token:
    secure: CVCDrMCszTQLBzPfJyz4SCbQx/9axUzHdVTd/WpzPhJtGjdDI7QGz2HwTCmrGV0yra4HccYsO+W+67+GjjfJ2YHpfWL/Dkpd6laXF8f0N9ru1jDZykzhcAYRYs9ZvftIvDPpkQT8dj52EP2OuurhUFGKD0Qe9QESVM1pwDzHJ/C5licplXe/bL4nnkojs1CuyrWL+IetwvnLd42Yh2bUxvkVNFJKt3Yz4KkgolE/6lQO72g74bXPamfnt8wS8//qVEZyw+jwrRUMi2NPQSy5X+5HT5tpbcGkdYhTHeaI6PWMdZXadj8xalRFhN37eq7gPOHw3x6d5Ibpd2LHeua94IjZqNcyAwwyBOhLnsfhRpz6CkKvO0ar+p6w1nyCZftezHnZvq2A2YBxhLt89HHIeOQGkgxlFKryvBFMFnprr9CPj0dxTDU2dZv7ipNEvnTopNjSrFBMwoTauux2L2dU8sSgXQZrML2sEfBiGRW5hN5jm8K7VDmuKGjx38NqetqwbudrBaV2zcmUfQ7xNg+cx+oqo+fP1T6zsOHWCas6WxSvgbjnVQkrLB/Yz34Ry6yUsPBpB37/Zi2dt12mEiSqYIaRmpHwPyw/1dkDHCEqPNobQcnzqFnJGLP5TqkiA15VrqZ4elFNLX0MPoXUMmbPM+FoLw11dnaUzBg3r9RVUm8=
  on:
    repo: pollen-robotics/website
    branch: master
