baseURL = "https://www.pollen-robotics.com/"
languageCode = "en-us"
title = "Pollen Robotics"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "sitemap", "RSS"]
googleAnalytics = "UA-92714924-1"

[params]
description = "Pollen Robotics site description"
brand = "Pollen Robotics"
