baseURL = "https://www.pollen-robotics.com/"
languageCode = "en-us"
title = "Pollen Robotics website"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
googleAnalytics = "UA-164958440-1"

theme = "pollen042020"
relativeURLs = true

[params]
description = "Pollen Robotics is a startup building open source interactive robots and artificial intelligences"
brand = "Pollen Robotics"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true